# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\"\xca\x01\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x16\n\x0epayment_method\x18\x04 \x01(\t\x12\x12\n\ncard_brand\x18\x05 \x01(\t\x12\x0c\n\x04\x62\x61nk\x18\x06 \x01(\t\x12\x17\n\x0fshipping_region\x18\x07 \x01(\t\x12\x18\n\x10shipping_address\x18\x08 \x01(\t\x12\x16\n\x0e\x63ustomer_email\x18\t \x01(\t\"2\n\rOrderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"&\n\x12OrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"%\n\x13OrderStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2y\n\x0cOrderService\x12,\n\x0b\x43reateOrder\x12\r.OrderRequest\x1a\x0e.OrderResponse\x12;\n\x0eGetOrderStatus\x12\x13.OrderStatusRequest\x1a\x14.OrderStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=17
  _globals['_ORDERREQUEST']._serialized_end=219
  _globals['_ORDERRESPONSE']._serialized_start=221
  _globals['_ORDERRESPONSE']._serialized_end=271
  _globals['_ORDERSTATUSREQUEST']._serialized_start=273
  _globals['_ORDERSTATUSREQUEST']._serialized_end=311
  _globals['_ORDERSTATUSRESPONSE']._serialized_start=313
  _globals['_ORDERSTATUSRESPONSE']._serialized_end=350
  _globals['_ORDERSERVICE']._serialized_start=352
  _globals['_ORDERSERVICE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
